// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Assignment_4.Test.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MoviesFeatureFeature : object, Xunit.IClassFixture<MoviesFeatureFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Movies.feature"
#line hidden
        
        public MoviesFeatureFeature(MoviesFeatureFeature.FixtureData fixtureData, Assignment_4_Test_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "movies feature", "All operations related to movies", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get existing movie from repository")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Get existing movie from repository")]
        public void GetExistingMovieFromRepository()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get existing movie from repository", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
 testRunner.When("a GET request is made \'api/movies/1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 6
 testRunner.Then(@"the response must be '{""id"":1,""name"":""M1"",""plot"":""plot1"",""producer"":{""id"":1,""name"":""P1"",""bio"":""--"",""gender"":""male"",""dob"":""2000-10-10T00:00:00""},""actors"":[{""id"":1,""name"":""A1"",""bio"":""--"",""gender"":""male"",""dob"":""2000-10-10T00:00:00""},{""id"":2,""name"":""A2"",""bio"":""--"",""gender"":""male"",""dob"":""2000-10-10T00:00:00""}],""yearOfRelease"":2000,""coverImage"":""www"",""genres"":[{""id"":1,""name"":""G1""},{""id"":2,""name"":""G2""}]}'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 7
 testRunner.And("status code \'200\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get non existing movie from repository")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Get non existing movie from repository")]
        public void GetNonExistingMovieFromRepository()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get non existing movie from repository", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
 testRunner.When("a GET request is made \'api/movies/0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.Then("status code \'404\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get all movies from repository")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Get all movies from repository")]
        public void GetAllMoviesFromRepository()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get all movies from repository", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 14
 testRunner.When("a GET request is made \'api/movies\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
 testRunner.Then(@"the response must be '[{""id"":1,""name"":""M1"",""plot"":""plot1"",""producer"":{""id"":1,""name"":""P1"",""bio"":""--"",""gender"":""male"",""dob"":""2000-10-10T00:00:00""},""actors"":[{""id"":1,""name"":""A1"",""bio"":""--"",""gender"":""male"",""dob"":""2000-10-10T00:00:00""},{""id"":2,""name"":""A2"",""bio"":""--"",""gender"":""male"",""dob"":""2000-10-10T00:00:00""}],""yearOfRelease"":2000,""coverImage"":""www"",""genres"":[{""id"":1,""name"":""G1""},{""id"":2,""name"":""G2""}]},{""id"":2,""name"":""M2"",""plot"":""plot1"",""producer"":{""id"":1,""name"":""P1"",""bio"":""--"",""gender"":""male"",""dob"":""2000-10-10T00:00:00""},""actors"":[{""id"":1,""name"":""A1"",""bio"":""--"",""gender"":""male"",""dob"":""2000-10-10T00:00:00""},{""id"":2,""name"":""A2"",""bio"":""--"",""gender"":""male"",""dob"":""2000-10-10T00:00:00""}],""yearOfRelease"":2000,""coverImage"":""www"",""genres"":[{""id"":1,""name"":""G1""},{""id"":2,""name"":""G2""}]}]'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 16
 testRunner.And("status code \'200\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Add new movie with invalid details")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Add new movie with invalid details")]
        [Xunit.InlineDataAttribute("", "2000", "Good movie", "1", "1,2", "1,2", "www.poster.com", "Invalid name", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2070", "Good movie", "1", "1,2", "1,2", "www.poster.com", "Invalid date", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "", "1", "1,2", "1,2", "www.poster.com", "Invalid plot", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "Good movie", "9", "1,2", "1,2", "www.poster.com", "Invalid producer id", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "Good movie", "1", "2,3", "1,2", "www.poster.com", "Invalid Actor id", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "Good movie", "1", "1,2", "2,3", "www.poster.com", "Invalid genre id", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "Good movie", "1", "1,2", "1,2", "", "Invalid cover", new string[0])]
        public void AddNewMovieWithInvalidDetails(string name, string yearOfRelease, string plot, string producerId, string actorsIds, string genresIds, string coverImage, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("YearOfRelease", yearOfRelease);
            argumentsOfScenario.Add("Plot", plot);
            argumentsOfScenario.Add("ProducerId", producerId);
            argumentsOfScenario.Add("ActorsIds", actorsIds);
            argumentsOfScenario.Add("GenresIds", genresIds);
            argumentsOfScenario.Add("CoverImage", coverImage);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new movie with invalid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
 testRunner.Given(string.Format("the following data is entered \'{{\"name\":\"{0}\", \"yearOfRelease\":{1}, \"plot\":\"{2}\"," +
                            " \"producerId\":{3},\"actorsIds\":\"{4}\",\"genresIds\":\"{5}\",\"coverImage\":\"{6}\"}}\'", name, yearOfRelease, plot, producerId, actorsIds, genresIds, coverImage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
 testRunner.When("a POST request is made \'api/movies\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
 testRunner.Then(string.Format("the response must be \'{0}\'", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
 testRunner.And("status code \'400\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add new movie with valid details")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Add new movie with valid details")]
        public void AddNewMovieWithValidDetails()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new movie with valid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 34
 testRunner.Given("the following data is entered \'{\"name\":\"ford\", \"yearOfRelease\":2000, \"plot\":\"plot" +
                        "1\", \"producerId\":1,\"actorsIds\":\"1,2\",\"genresIds\":\"1,2\",\"coverImage\":\"www\"}\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 35
 testRunner.When("a POST request is made \'api/movies\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
 testRunner.Then("status code \'201\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
 testRunner.And("the response must be \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Delete existing movie from repository")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Delete existing movie from repository")]
        public void DeleteExistingMovieFromRepository()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete existing movie from repository", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 40
 testRunner.When("a DELETE request is made \'api/movies/1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 41
 testRunner.Then("status code \'200\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Delete non existing movie from repository")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Delete non existing movie from repository")]
        public void DeleteNonExistingMovieFromRepository()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete non existing movie from repository", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 44
 testRunner.When("a DELETE request is made \'api/movies/0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 45
 testRunner.Then("status code \'404\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update non existing movie from repository")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Update non existing movie from repository")]
        public void UpdateNonExistingMovieFromRepository()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update non existing movie from repository", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 48
 testRunner.Given("the following data is entered \'{\"name\":\"ford\", \"yearOfRelease\":2000, \"plot\":\"plot" +
                        "1\", \"producerId\":1,\"actorsIds\":\"1,2\",\"genresIds\":\"1,2\",\"coverImage\":\"www\"}\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 49
 testRunner.When("a PUT request is made \'api/movies/0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
 testRunner.Then("status code \'400\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Update existing movie with invalid details")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Update existing movie with invalid details")]
        [Xunit.InlineDataAttribute("", "2000", "Good movie", "1", "1,2", "1,2", "www.poster.com", "Invalid name", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2070", "Good movie", "1", "1,2", "1,2", "www.poster.com", "Invalid date", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "", "1", "1,2", "1,2", "www.poster.com", "Invalid plot", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "Good movie", "9", "1,2", "1,2", "www.poster.com", "Invalid producer id", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "Good movie", "1", "2,3", "1,2", "www.poster.com", "Invalid Actor id", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "Good movie", "1", "1,2", "2,3", "www.poster.com", "Invalid genre id", new string[0])]
        [Xunit.InlineDataAttribute("ford", "2000", "Good movie", "1", "1,2", "1,2", "", "Invalid cover", new string[0])]
        public void UpdateExistingMovieWithInvalidDetails(string name, string yearOfRelease, string plot, string producerId, string actorsIds, string genresIds, string coverImage, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("YearOfRelease", yearOfRelease);
            argumentsOfScenario.Add("Plot", plot);
            argumentsOfScenario.Add("ProducerId", producerId);
            argumentsOfScenario.Add("ActorsIds", actorsIds);
            argumentsOfScenario.Add("GenresIds", genresIds);
            argumentsOfScenario.Add("CoverImage", coverImage);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update existing movie with invalid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 53
 testRunner.Given(string.Format("the following data is entered \'{{\"name\":\"{0}\", \"yearOfRelease\":{1}, \"plot\":\"{2}\"," +
                            " \"producerId\":{3},\"actorsIds\":\"{4}\",\"genresIds\":\"{5}\",\"coverImage\":\"{6}\"}}\'", name, yearOfRelease, plot, producerId, actorsIds, genresIds, coverImage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 54
 testRunner.When("a PUT request is made \'api/movies/1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
 testRunner.Then(string.Format("the response must be \'{0}\'", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 56
 testRunner.And("status code \'400\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Update movie with valid details")]
        [Xunit.TraitAttribute("FeatureTitle", "movies feature")]
        [Xunit.TraitAttribute("Description", "Update movie with valid details")]
        public void UpdateMovieWithValidDetails()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update movie with valid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 68
 testRunner.Given("the following data is entered \'{\"name\":\"ford\", \"yearOfRelease\":2000, \"plot\":\"plot" +
                        "1\", \"producerId\":1,\"actorsIds\":\"1,2\",\"genresIds\":\"1,2\",\"coverImage\":\"www\"}\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 69
 testRunner.When("a PUT request is made \'api/movies/1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 70
 testRunner.Then("status code \'200\' is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                MoviesFeatureFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                MoviesFeatureFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
